export const FETCH_POSTS = "FETCH_POSTS"
export const FETCH_ONE_POST = "FETCH_ONE_POST"
export const CREATE_POST = "CREATE_POST"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"